import { Router } from "express";
import health from "./health.js";
import stack from "./stack.js";
import models from "./models.js";
import workspace from "./workspace.js";
import system from "./system.js";
import updates from "./updates.js";
import continueRoute from "./continue.js";
import studios from "./studios.js";
import remote from "./remote.js";
import chat from "./chat.js";
import filebrowser from "./filebrowser.js";
import context from "./context.js";
import intelligence from "./intelligence.js";
import integrations from "./integrations.js";
import usage from "./usage.js";
import updater from "./updater.js";
import repair from "./repair.js";
import kernel from "./kernel.js";
import observability from "./observability.js";
import tasks from "./tasks.js";
import rollback from "./rollback.js";
import sessions from "./sessions.js";
import stt from "./stt.js";
import tts from "./tts.js";
import ragRoute from "./rag.js";
import evidence from "./evidence.js";
import web from "./web.js";
import benchmark from "./benchmark.js";
import pinboard from "./pinboard.js";
import tokenBudget from "./token-budget.js";
import timetravel from "./timetravel.js";
import plugins from "./plugins.js";
import worldgui from "./worldgui.js";
import foundation from "./foundation.js";
import runtimeMode from "./runtime-mode.js";
import providerPolicy from "./provider-policy.js";
import approvals from "./approvals.js";
import voice from "./voice.js";
import business from "./business.js";
import itSupport from "./it-support.js";
import homelab from "./homelab.js";

const router = Router();

router.use(health);
router.use(stack);
router.use(models);
router.use(workspace);
router.use(system);
router.use(updates);
router.use(continueRoute);
router.use(studios);
router.use(remote);
router.use(chat);
router.use(sessions);
router.use(filebrowser);
router.use(context);
router.use(intelligence);
router.use(integrations);
router.use(usage);
router.use(updater);
router.use(repair);
router.use(kernel);
router.use(observability);
router.use(tasks);
router.use(rollback);
router.use(stt);
router.use(tts);
router.use(ragRoute);
router.use(evidence);
router.use(web);
router.use(benchmark);
router.use(pinboard);
router.use(tokenBudget);
router.use(timetravel);
router.use(plugins);
router.use(worldgui);
router.use(foundation);
router.use(approvals);
router.use(runtimeMode);
router.use(providerPolicy);
router.use(voice);
router.use(business);
router.use(itSupport);
router.use(homelab);

export default router;
